language: python
dist: xenial
sudo: required
matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
      env: TOXENV=py39
install:
  - python3 -m pip install tox
script:
  - tox
